on: workflow_dispatch

name: Publish VSC Extension (Manual)
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: "pnpm"

            - name: Install deps w/ yarn
              working-directory: ./packages/ripple-vscode-plugin
              run: yarn install

            - name: Build VSIX
              working-directory: ./packages/ripple-vscode-plugin
              run: pnpx @vscode/vsce package

            - name: Upload VSIX
              uses: actions/upload-artifact@v4
              with:
                  name: ripple-vscode-plugin VSIX
                  path: ./packages/ripple-vscode-plugin/*.vsix

    publish-vsm:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download VSIX
              uses: actions/download-artifact@v5
              with:
                  name: ripple-vscode-plugin VSIX

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10

            - name: Publish to VSM
              run: pnpx -- @vscode/vsce publish -i *.vsix
              env:
                  VSCE_PAT: ${{ secrets.VSM_TOKEN }}

    publish-ovsx:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download VSIX
              uses: actions/download-artifact@v5
              with:
                  name: ripple-vscode-plugin VSIX

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10

            - name: Publish to OVSX
              run: pnpx ovsx publish *.vsix
              env:
                  OVSX_PAT: ${{ secrets.OVSX_TOKEN }}
